- name: configure mysql server
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseAPP@1
  tasks:
    - name: Install Mysql libraries
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
        - cryptography
        - PyMySQL

    - name: Install mySQL server
      ansible.builtin.package:
        name: mysql-server
        state: present

    - name: start and enable mysql server
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: connect to mysql server
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_host: ansible.mysql.practice25.online
      register: mysql_info
      ignore_errors: true

    - name: print the output
      ansible.builtin.debug:
        msg: "mysql_info {{ mysql_info }}"

    - name: setup root login_password
      ansible.builtin.command: "mysql_secure_installation --set-root--pass  ExpenseAPP@1"
      when: mysql_info.failed is true
